italia/iam-proxy-italia

- README.md
* Added libpcre3 libpcre3-dev dependencies
* created directories before get metadata
> Little correction in README

- example/plugins/backends/spidsaml2_backend.yaml
- example/static/disco.html
- phonenumber in metadata without white spaces
> DiscoPage html with SPID usage text

- README.md
> Fixed repository url in readme

- README.md
> Fixed config files path

- example/backends/spidsaml2_validator.py
> Fix test 99

- example/run.sh
https://github.com/italia/Satosa-Saml2Spid/issues/75
> fix: Python env var with alpine3.16 

- README.md
- compose-Satosa-Saml2Spid/README.md
- compose-Satosa-Saml2Spid/docker-compose.yml
- example/run.sh
> fix enviroment's name and echo

- .github/workflows/python-app.yml
- Docker-compose/docker-compose.yml
- Docker-compose/run-docker-compose.sh
- requirements.txt
- Temporary install `pyeudiw` from Github dev branch until next release.
- Fix CI host missing dependency.
- Minor improvements to Github action
Should fix #74
> Fix CI pre-release

- Docker-compose/docker-compose.yml
This PR enables the use of python debugger within a dockerized context
> debug-docker-attach

- example/entrypoint.sh
Proposal solution to issue #144
> feat: handle retries when fetching from remote registry

- example/attributes-map/satosa_spid_uri_hybrid.py
> Error in OID email code

- Docker-compose/nginx/conf.d/default.conf
This is a DRAFT and SHOULD NOT be merged until integrations tests for https://github.com/italia/eudi-wallet-it-python/issues/296 are completed and passed.
This PR includes a configuration designed to overcome some limitations on which endpoints can be exposed by a satosa module.
Edit: opened https://github.com/italia/eudi-wallet-it-python/pull/328
> feat: route configuration for jar-issuer endpoint

- example/backends/spidsaml2.py
- example/plugins/backends/spidsaml2_backend.yaml
Aggiunta opzione per aggiungere l'estensione `"spid:aggregated"`, aggiungendo `Aggregated: ''` ad un elemento di `contact_person`
> feat: added support for aggregated contact person in case of spid aggregator

- README-DEV.md
- README.idpy.forks.mngmnt.md
- gallery/iam-proxy.svg
- pyproject.toml
This PR aligns the depedencies with the pplnx's forks
> Satosa and PySAML2 forks alignment

- iam-proxy-italia-project/conf/frontends/openid4vci_frontend.yaml
Align for [#477](https://github.com/italia/eudi-wallet-it-python/issues/477)
> feat: openid4vci dpop_signing_alg_values_supported configuration

- iam-proxy-italia-project/conf/backends/pyeudiw_backend.yaml
- iam-proxy-italia-project/conf/frontends/openid4vci_frontend.yaml
Alignments for https://github.com/italia/eudi-wallet-it-python/issues/478
> rev: MongoDB schema and collection naming review

- iam-proxy-italia-project/conf/backends/pyeudiw_backend.yaml
Resolve [eudi-wallet-it-python #474](https://github.com/italia/eudi-wallet-it-python/issues/474)
> fix: integration_test

- Docker-compose/docker-compose.yml
> fix: docker-compose for alpine updated to 3.22

- .gitignore
- Docker-compose/docker-compose.yml
- Dockerfile
A new version of alpine is required to satisfy dependency requirements about python and cryptography
> feat: alpine updated to 3.22, python requirements and image version set to 3.0

- .gitguardian.yaml
- Docker-compose/docker-compose.yml
- Docker-compose/pyeudiw-healthcheck.sh
> Docker compose Healthchecks improvements
